### live server test
GET http://localhost:7000

### live server test
GET http://localhost:7000/api/v1/register

### USER user registration
POST http://localhost:7000/api/v1/register
Content-Type: application/json

{
    "fName": "Prem",
    "lName": "Acharya",
    "dob":  "2020-02-20",
    "phone":"044444444",
    "email" :"avinashandrew3@gmail.com",
    "password": "123456",
    "address": "somewhere in sydeny"
}

### USER user registration
POST http://localhost:7000/api/v1/login
Content-Type: application/json

{
    "email": "avinashandrew3@gmail.com",
    "password": "123456"
}



### USER user registration
POST http://localhost:7000/api/v1/register/reqOtp
Content-Type: application/json

{
    "email" :"avinashandrew3@gmail.com"
}


### USER user registration
PATCH http://localhost:7000/api/v1/register/reqOtp
Content-Type: application/json

{
    "email" :"avinashandrew3@gmail.com",
    "password":"12345",
    "otp": "412798"
}