### live server test
GET http://localhost:8000

### live server test
GET http://localhost:8000/api/v1/register

### USER user registration
POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "fName": "Prem",
    "lName": "Acharya",
    "dob":  "2020-02-20",
    "phone":"044444444",
    "email" : "a@a.com",
    "password": "123456",
    "address": "somewhere in sydeny"
}

### USER user registration
POST http://localhost:8000/api/v1/login
Content-Type: application/json